[project]
name = "pipcanary"
version = "0.1.0"
authors = [
  { name="Sebastian Kuebeck", email="sebastian.kuebeck@encab.io" },
]
license-files = ['LICENSE']
description = "Supply Chain Attack prevention tool"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Topic :: Security", 
    "Environment :: Console"
]


dependencies = [
  "distlib<=0.4.0",
  "filelock<=3.25.2",
  "platformdirs<=4.9.4",
  "tomli<=2.4.1",
  "virtualenv<=21.2.0",
  "pip==26.1",
  "python-discovery<=1.2.2"
]

[project.urls]
"Homepage" = "https://github.com/sebastian-kuebeck/pipcanary"
"Documentation" = "https://github.com/sebastian-kuebeck/pipcanary"
"Bug Tracker" = "https://github.com/sebastian-kuebeck/pipcanary"

[project.scripts]
pipcanary = "pipcanary.pipcanary:pipcanary"

[tool.setuptools.package-data]
pipcanary = ["src/pipcanary/sbpip_scan.sh", "src/pipcanary/spip_scan.sh"]

[tool.ruff]
line-length = 120