[tox]
skipsdist = True
envlist = python3.10, python3.11, python3.12, python3.13, python3.14, python3.15

[testenv]
deps =
    -r requirements.txt
commands =
    pip install -e .[all]
    pyright src tests
	ruff check src tests
    python -m unittest discover -v -s tests/unit -p '*_test.py'
